---
- name: Install helm from source
  ansible.builtin.get_url:
    url: https://get.helm.sh/helm-v3.15.2-linux-amd64.tar.gz 
    dest: /tmp/helm-v3.15.2-linux-amd64.tar.gz 
    mode: 0644

- name: Ensure target directory exists
  ansible.builtin.file:
    path: /tmp/helm
    state: directory

- name: Extract Helm tarball
  ansible.builtin.unarchive:
    src: /tmp/helm-v3.15.2-linux-amd64.tar.gz 
    dest: /tmp/helm/
    remote_src: yes

- name: Copy helm binary to /usr/local/bin
  ansible.builtin.copy:
    src: /tmp/helm/linux-amd64/helm
    dest: /usr/local/bin/helm
    mode: '0755'
  become: true 

- name: Remove tmp dir
  ansible.builtin.file:
    path: /tmp/helm
    state: absent
  become: true

- name: Remove tarball
  ansible.builtin.file:
    path: /tmp/helm-v3.15.2-linux-amd64.tar.gz
    state: absent
  become: true


- name: Download helmfile 
  ansible.builtin.get_url:
    url: https://github.com/helmfile/helmfile/releases/download/v0.165.0/helmfile_0.165.0_linux_amd64.tar.gz 
    dest: /tmp/helmfile_0.165.0_linux_amd64.tar.gz 
    mode: 0644

- name: Ensure target directory exists
  ansible.builtin.file:
    path: /tmp/helmfile
    state: directory

- name: Extract Helm tarball
  ansible.builtin.unarchive:
    src: /tmp/helmfile_0.165.0_linux_amd64.tar.gz 
    dest: /tmp/helmfile/
    remote_src: yes

- name: Copy helm binary to /usr/local/bin
  ansible.builtin.copy:
    src: /tmp/helmfile/helmfile
    dest: /usr/local/bin/helmfile
    mode: '0755'
  become: true 

- name: Remove tmp dir
  ansible.builtin.file:
    path: /tmp/helmfile
    state: absent
  become: true

- name: Remove tarball
  ansible.builtin.file:
    path: /tmp/helmfile_0.165.0_linux_amd64.tar.gz 
    state: absent
  become: true


