---
- name: "Dependencies"
  ansible.builtin.apt:
    pkg:
      - xsel
      - xclip
  state: present
  become: true

- name: "Install tmux"
  ansible.builtin.apt:
    name: tmux
    state: present
  become: true

- name: "Install TPM"
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
  become: no
